### ISSUE TITLE
Is this abandonned?

### ISSUE THREAD

**Issue by bendem** [Fedict/fts-beidconnect#1]
Hello, I see that the [last supported fedora version](https://eid.static.bosa.fgov.be/rpm/fedora/) is 36 which went of of support earlier this year. Is this software and sign.belgium.be being abandoned? It's one of the really useful services for people that do/can not use windows and it'd be sad to see it go to waste.

**Comment by kennethVDL** [comment]
Hello, neither BeIDConnect nor sign.belgium.be have been abandoned.
This has been updated today, apologies for the delay. Could you try again and let us know if this is again working as it should?

**Comment by bendem** [comment]
Awesome, thanks for the quick update!

**Comment by bendem** [comment]
I closed too fast, 37 is fine, but the 38 repo is empty.

**Comment by bendem** [comment]
Aaaand, it's there now 😇
